version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "build(actions): "
    groups:
      otel:
        patterns:
          - "opentelemetry*"
    labels:
      - "dependencies"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "build(deps): "
      prefix-development: "build(deps-dev): "
    groups:
      pytest:
        patterns:
          - "pytest*"
    labels:
      - "dependencies"