version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    image: xes-uff
    container_name: xes-uff
    ports:
      - "8000:8080"
    volumes:
      - ./src:/app/src
      - ./main.py:/app/main.py
      - ./poetry.lock:/app/poetry.lock
      - ./pyproject.toml:/app/pyproject.toml
    environment:
      _CREDENTIALS: ${_CREDENTIALS:-service.json}
      _PROJECT_ID: ${_PROJECT_ID:-xes-tcc}
      _PUBSUB_TOPIC: ${_PUBSUB_TOPIC:-processor-queue}
      _BUCKET_PATH: ${_BUCKET_PATH:-conversion-files}
      _LOG_LEVEL: ${_LOG_LEVEL:-DEBUG}
      _ORIGIN: ${_ORIGIN:-http://dev.localhost}
      _ENV: ${_ENV:-local}
      _EXPORT_TO: ${_EXPORT_TO:-console}
      _SENDGRID_KEY: ${_SENDGRID_KEY}
      _BASE_URL: ${_BASE_URL:-http://localhost:8080}
      _SENDER_EMAIL: gustavo_albino@id.uff.br
      PUBSUB_EMULATOR_HOST: "${PUBSUB_EMULATOR_HOST}"
      STORAGE_EMULATOR_HOST: ${STORAGE_EMULATOR_HOST}
    command: make server

  storage:
    image: oittaa/gcp-storage-emulator:latest
    command: start --host=storage --port=9023 --default-bucket=conversion-files
    restart: unless-stopped
    ports:
      - 9023:9023
    volumes:
      - ./cloudstorage:/storage
    profiles:
      - storage

  pubsub:
    image: us-east1-docker.pkg.dev/xes-tcc/pubsub-emulator/pubsub-emulator:1.0.1
    platform: linux/amd64
    ports:
      - 8085:8085
    environment:
      PUBSUB_PROJECT_ID: ${_PROJECT_ID:-xes-tcc}
      PUBSUB_CONFIG: |
        [
          {
            "name": "processor-queue",
            "subscriptions": [
              {"id": "process-api", "endpoint": "http://host.docker.internal:8000/api/v1/_pubsub"}
            ]
          }
        ]
    profiles:
    - pubsub